version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '3000:8080'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  